version: '3.4'
services:
  postgres:
    image: "postgres:13.1"
    restart: always
    ports:
      - '5432:5432'
    expose:
      - '5432'
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data/
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
        interval: 30s
        timeout: 30s
        retries: 5
volumes:
  postgres: {}
